const mysql = require('mysql2/promise');
require('dotenv').config();

const PORT = process.env.PORT || 3000;
const BASE_URL = process.env.BASE_URL || `http://localhost:${PORT}/api`;
let cookie = '';
let createdOrderId = null;
let createdProductId = null;
let sellerId = null;
let buyerId = null;

function resetCookie() {
    cookie = '';
}

async function request(endpoint, method = 'GET', body = null) {
    const headers = {
        'Content-Type': 'application/json'
    };
    if (cookie) {
        headers['Cookie'] = cookie;
    }
    const options = {
        method,
        headers
    };
    if (body) {
        options.body = JSON.stringify(body);
    }
    const res = await fetch(`${BASE_URL}${endpoint}`, options);

    const setCookie = res.headers.get('set-cookie');
    if (setCookie) {
        const match = setCookie.split(';')[0];
        cookie = match;
    }

    const text = await res.text();
    try {
        return { status: res.status, data: JSON.parse(text) };
    } catch (e) {
        return { status: res.status, data: text };
    }
}

async function runTests() {
    console.log("=========================================");
    console.log("Starting E2E Tests with DB Verification");
    console.log("=========================================");

    const timestamp = Date.now();

    const db = await mysql.createConnection({
        host: process.env.DB_HOST || 'localhost',
        user: process.env.DB_USER || 'root',
        password: process.env.DB_PASS || '',
        database: process.env.DB_NAME || 'unimart'
    });

    try {
        // 1. Register Seller
        const sellerEmail = `seller_${timestamp}@hct.ac.ae`;
        const buyerEmail = `buyer_${timestamp}@hct.ac.ae`;

        console.log(`\n--- 1. Testing Seller Registration ---`);
        let res = await request('/auth/register', 'POST', {
            name: 'E2E Seller',
            email: sellerEmail,
            password: 'password123',
            phone: '0500000000'
        });
        console.log('Seller Register Response:', res.status, res.data);
        if (res.status !== 201) throw new Error("Seller registration failed");

        // Verify DB
        let [sellerRows] = await db.query('SELECT * FROM users WHERE email = ?', [sellerEmail]);
        if (sellerRows.length === 0) throw new Error("Seller not found in DB");
        sellerId = sellerRows[0].id;
        console.log('✅ Seller verified in database:', sellerRows[0].email);

        // 2. Login Seller
        console.log(`\n--- 2. Testing Seller Login ---`);
        res = await request('/auth/login', 'POST', {
            email: sellerEmail,
            password: 'password123'
        });
        console.log('Seller Login Response:', res.status, res.data);
        if (res.status !== 200 || !res.data.user) throw new Error("Seller login failed");
        console.log('✅ Seller session cookie acquired');

        // 3. Fetch Categories & Create Product
        console.log(`\n--- 3. Testing Products ---`);
        res = await request('/categories', 'GET');
        console.log(`Categories Fetched:`, res.status);

        res = await request('/products', 'POST', {
            title: 'E2E Test Product',
            description: 'This is a test product generated by the e2e script',
            price: 49.99,
            category_id: 1,
            image_url: ''
        });
        console.log('Create Product Response:', res.status, res.data);
        let productId = res.data.productId;
        createdProductId = productId;

        // Verify DB for new product
        if (!productId) throw new Error("Product ID not returned properly. " + JSON.stringify(res.data));
        let [prodDB] = await db.query('SELECT * FROM products WHERE id = ?', [productId]);
        if (prodDB.length === 0) throw new Error("Product not saved to DB");
        console.log('✅ Product verified in DB:', prodDB[0].title);

        // 4. Register and Login Buyer
        console.log(`\n--- 4. Testing Buyer Registration and Login ---`);
        resetCookie();
        res = await request('/auth/register', 'POST', {
            name: 'E2E Buyer',
            email: buyerEmail,
            password: 'password123',
            phone: '0501111111'
        });
        console.log('Buyer Register Response:', res.status, res.data);
        if (res.status !== 201) throw new Error("Buyer registration failed");

        let [buyerRows] = await db.query('SELECT * FROM users WHERE email = ?', [buyerEmail]);
        if (buyerRows.length === 0) throw new Error("Buyer not found in DB");
        buyerId = buyerRows[0].id;
        console.log('✅ Buyer verified in database:', buyerRows[0].email);

        res = await request('/auth/login', 'POST', {
            email: buyerEmail,
            password: 'password123'
        });
        console.log('Buyer Login Response:', res.status, res.data);
        if (res.status !== 200 || !res.data.user) throw new Error("Buyer login failed");
        console.log('✅ Buyer session cookie acquired');

        // 5. Add to Cart
        console.log(`\n--- 5. Testing Cart ---`);
        res = await request('/cart', 'POST', {
            product_id: productId,
            quantity: 1
        });
        console.log('Add to Cart Response:', res.status, res.data);
        if (res.status !== 201) throw new Error("Add to cart failed");

        res = await request('/cart', 'GET');
        console.log('Get Cart Response:', res.status, 'Items:', res.data.length);
        if (res.data.length === 0) throw new Error("Cart is empty after adding item");

        // Verify DB
        let [cartDB] = await db.query('SELECT * FROM cart_items WHERE user_id = ? AND product_id = ?', [buyerRows[0].id, productId]);
        if (cartDB.length === 0) throw new Error("Cart item not saved to DB");
        console.log('✅ Cart item verified in DB');

        // 6. Checkout / Place Order
        console.log(`\n--- 6. Testing Order Placement ---`);
        res = await request('/orders', 'POST', {
            address: '123 University St, Tech Building',
            phone: '0501234567'
        });
        console.log('Place Order Response:', res.status, res.data);
        if (res.status !== 201) throw new Error("Order placement failed");

        let orderId = res.data.orderId;
        createdOrderId = orderId;

        // View Orders
        res = await request('/orders', 'GET');
        console.log('Get Orders Response:', res.status, 'Order Count:', res.data.length);

        // Verify DB
        let [orderDB] = await db.query('SELECT * FROM orders WHERE id = ?', [orderId]);
        if (orderDB.length === 0) throw new Error("Order not saved to DB");
        console.log('✅ Order verified in DB:', orderDB[0]);

        let [orderItemsDB] = await db.query('SELECT * FROM order_items WHERE order_id = ?', [orderId]);
        if (orderItemsDB.length === 0) throw new Error("Order items not saved to DB");
        console.log(`✅ Order items verified in DB (${orderItemsDB.length} item(s)):`, orderItemsDB[0]);

        // Check if cart is cleared
        let [cartAfterOrder] = await db.query('SELECT * FROM cart_items WHERE user_id = ?', [buyerRows[0].id]);
        if (cartAfterOrder.length !== 0) throw new Error("Cart not cleared after order");
        console.log('✅ Cart cleared in DB successfully');

        console.log(`\n=========================================`);
        console.log(`🎉 ALL E2E TESTS PASSED SUCCESSFULLY!`);
        console.log(`=========================================`);

    } catch (err) {
        console.error("\n❌ TEST FAILED:", err.message);
        process.exitCode = 1;
    } finally {
        // Cleanup test data to prevent DB pollution from repeated runs
        try {
            console.log(`\n--- Cleaning up test data ---`);
            if (createdOrderId) {
                await db.query('DELETE FROM orders WHERE id = ?', [createdOrderId]);
            }
            if (createdProductId) {
                await db.query('DELETE FROM products WHERE id = ?', [createdProductId]);
            }
            if (buyerId || sellerId) {
                await db.query('DELETE FROM users WHERE id IN (?)', [[buyerId, sellerId].filter(Boolean)]);
            }
            console.log('✅ Test data cleaned up');
        } catch (cleanupErr) {
            console.warn('⚠️  Cleanup warning:', cleanupErr.message);
        }
        await db.end();
    }
}

runTests();
