const mysql = require('mysql2/promise');

const BASE_URL = 'http://localhost:3000/api';
let cookie = '';

async function request(endpoint, method = 'GET', body = null) {
    const headers = {
        'Content-Type': 'application/json'
    };
    if (cookie) {
        headers['Cookie'] = cookie;
    }
    const options = {
        method,
        headers
    };
    if (body) {
        options.body = JSON.stringify(body);
    }
    const res = await fetch(`${BASE_URL}${endpoint}`, options);

    const setCookie = res.headers.get('set-cookie');
    if (setCookie) {
        const match = setCookie.split(';')[0];
        cookie = match;
    }

    const text = await res.text();
    try {
        return { status: res.status, data: JSON.parse(text) };
    } catch (e) {
        return { status: res.status, data: text };
    }
}

async function runTests() {
    console.log("=========================================");
    console.log("Starting E2E Tests with DB Verification");
    console.log("=========================================");

    const db = await mysql.createConnection({
        host: 'localhost',
        user: 'root',
        password: '',
        database: 'unimart'
    });

    try {
        // 1. Register User
        const testEmail = `testuser_${Date.now()}@hct.ac.ae`;
        console.log(`\n--- 1. Testing Registration ---`);
        let res = await request('/auth/register', 'POST', {
            name: 'Test User',
            email: testEmail,
            password: 'password123',
            phone: '0500000000'
        });
        console.log('Register Response:', res.status, res.data);
        if (res.status !== 201) throw new Error("Registration failed");

        // Verify DB
        let [users] = await db.query('SELECT * FROM users WHERE email = ?', [testEmail]);
        if (users.length === 0) throw new Error("User not found in DB");
        console.log('✅ User verified in database:', users[0].email);

        // 2. Login User
        console.log(`\n--- 2. Testing Login ---`);
        res = await request('/auth/login', 'POST', {
            email: testEmail,
            password: 'password123'
        });
        console.log('Login Response:', res.status, res.data);
        if (res.status !== 200 || !res.data.user) throw new Error("Login failed");
        console.log('✅ Session cookie acquired');

        // 3. Fetch Categories & Products
        console.log(`\n--- 3. Testing Products ---`);
        res = await request('/categories', 'GET');
        console.log(`Categories Fetched:`, res.status);

        // Create a new product
        res = await request('/products', 'POST', {
            title: 'E2E Test Product',
            description: 'This is a test product generated by the e2e script',
            price: 49.99,
            category_id: 1,
            image_url: ''
        });
        console.log('Create Product Response:', res.status, res.data);
        let productId = res.data.productId;

        // Verify DB for new product
        if (!productId) throw new Error("Product ID not returned properly. " + JSON.stringify(res.data));
        let [prodDB] = await db.query('SELECT * FROM products WHERE id = ?', [productId]);
        if (prodDB.length === 0) throw new Error("Product not saved to DB");
        console.log('✅ Product verified in DB:', prodDB[0].title);

        // 4. Add to Cart
        console.log(`\n--- 4. Testing Cart ---`);
        res = await request('/cart', 'POST', {
            product_id: productId,
            quantity: 1
        });
        console.log('Add to Cart Response:', res.status, res.data);
        if (res.status !== 201) throw new Error("Add to cart failed");

        res = await request('/cart', 'GET');
        console.log('Get Cart Response:', res.status, 'Items:', res.data.length);
        if (res.data.length === 0) throw new Error("Cart is empty after adding item");

        // Verify DB
        let [cartDB] = await db.query('SELECT * FROM cart_items WHERE user_id = ? AND product_id = ?', [users[0].id, productId]);
        if (cartDB.length === 0) throw new Error("Cart item not saved to DB");
        console.log('✅ Cart item verified in DB');

        // 5. Checkout / Place Order
        console.log(`\n--- 5. Testing Order Placement ---`);
        res = await request('/orders', 'POST', {
            address: '123 University St, Tech Building',
            phone: '0501234567'
        });
        console.log('Place Order Response:', res.status, res.data);
        if (res.status !== 201) throw new Error("Order placement failed");

        let orderId = res.data.orderId;

        // View Orders
        res = await request('/orders', 'GET');
        console.log('Get Orders Response:', res.status, 'Order Count:', res.data.length);

        // Verify DB
        let [orderDB] = await db.query('SELECT * FROM orders WHERE id = ?', [orderId]);
        if (orderDB.length === 0) throw new Error("Order not saved to DB");
        console.log('✅ Order verified in DB:', orderDB[0]);

        let [orderItemsDB] = await db.query('SELECT * FROM order_items WHERE order_id = ?', [orderId]);
        if (orderItemsDB.length === 0) throw new Error("Order items not saved to DB");
        console.log(`✅ Order items verified in DB (${orderItemsDB.length} item(s)):`, orderItemsDB[0]);

        // Check if cart is cleared
        let [cartAfterOrder] = await db.query('SELECT * FROM cart_items WHERE user_id = ?', [users[0].id]);
        if (cartAfterOrder.length !== 0) throw new Error("Cart not cleared after order");
        console.log('✅ Cart cleared in DB successfully');

        console.log(`\n=========================================`);
        console.log(`🎉 ALL E2E TESTS PASSED SUCCESSFULLY!`);
        console.log(`=========================================`);

    } catch (err) {
        console.error("\n❌ TEST FAILED:", err.message);
    } finally {
        await db.end();
    }
}

runTests();
